const pmData = {
  "modulos": [
    {
      "id": "01.1.1",
      "nombre": "Entidad",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [
        {
          "fecha": "2026-06-12",
          "desarrollador": "Julio Barrales",
          "avance_reportado": 1,
          "notas": "Desarrollo inicial completado al 100%"
        },
        {
          "fecha": "2026-06-12",
          "desarrollador": "Daryl Olazarán",
          "avance_reportado": 1,
          "notas": "Iteración de rediseño completada al 100%"
        }
      ],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.1.2",
      "nombre": "Ejercicios Fiscales",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [
        {
          "fecha": "2026-06-12",
          "desarrollador": "Julio Barrales",
          "avance_reportado": 1,
          "notas": "Desarrollo inicial completado al 100%"
        },
        {
          "fecha": "2026-06-12",
          "desarrollador": "Daryl Olazarán",
          "avance_reportado": 1,
          "notas": "Iteración de rediseño completada al 100%"
        }
      ],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.1.3",
      "nombre": "Períodos Contables",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [
        {
          "fecha": "2026-06-12",
          "desarrollador": "Julio Barrales",
          "avance_reportado": 1,
          "notas": "Desarrollo inicial completado al 100%"
        },
        {
          "fecha": "2026-06-12",
          "desarrollador": "Daryl Olazarán",
          "avance_reportado": 1,
          "notas": "Iteración de rediseño completada al 100%"
        }
      ],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.1",
      "nombre": "Unidades Administrativas",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.2",
      "nombre": "COG",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.3",
      "nombre": "Programas",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.4",
      "nombre": "Fuentes Financiamiento",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.5",
      "nombre": "CUCOP",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.6",
      "nombre": "Subprogramas",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.7",
      "nombre": "CRI",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.8",
      "nombre": "Proyectos",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.2.9",
      "nombre": "Centros Costos",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.3.1",
      "nombre": "Proveedores",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.3.2",
      "nombre": "Subtipo Proveedor",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.3.3",
      "nombre": "Empleados",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.3.4",
      "nombre": "Terceros Inst.",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.3.5",
      "nombre": "Terceros",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.4.1",
      "nombre": "Bancos",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.4.2",
      "nombre": "Chequeras",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.4.3",
      "nombre": "Conceptos Banc.",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.5.1",
      "nombre": "Sistemas",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.5.2",
      "nombre": "Subsistemas",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.5.3",
      "nombre": "Módulos",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.5.4",
      "nombre": "Roles de Sistema",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.6.1",
      "nombre": "Clasificación Func.",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.6.2",
      "nombre": "Función",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Daryl",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.6.3",
      "nombre": "Momentos",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "01.6.4",
      "nombre": "Tipo Documento",
      "sistema": "Configuración Base",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.1.1",
      "nombre": "Clave Presupuestal",
      "sistema": "Presupuestos",
      "subsistema": "Registro",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 1,
      "visitas": [],
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.1.2",
      "nombre": "Presupuesto Autorizado",
      "sistema": "Presupuestos",
      "subsistema": "Registro",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.1.3",
      "nombre": "Bienes Inmuebles",
      "sistema": "Presupuestos",
      "subsistema": "Catálogo",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.1.4",
      "nombre": "Registro de Contratos",
      "sistema": "Presupuestos",
      "subsistema": "Catálogo",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.1",
      "nombre": "Calendarización",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.2",
      "nombre": "Recalendarización",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.3",
      "nombre": "Transferencias",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 1,
      "visitas": [],
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.4",
      "nombre": "Amp. y Red. (Egresos)",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.5",
      "nombre": "Compromiso Arrend.",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.6",
      "nombre": "Validación de afectaciones",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.2.7",
      "nombre": "Cierre presupuestal mensual",
      "sistema": "Presupuestos",
      "subsistema": "Proceso",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.1",
      "nombre": "Suficiencias Presup.",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.2",
      "nombre": "Bitácora de Adecuaciones",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.3",
      "nombre": "Gastos de Operación (UA)",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4",
      "nombre": "Consola Central Reportes",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4.1",
      "nombre": "Avance presupuestal",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4.2",
      "nombre": "EAepe - Clasif. Admin.",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4.3",
      "nombre": "EAepe - Clasif. Económica",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4.4",
      "nombre": "EAepe - Objeto del Gasto",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4.5",
      "nombre": "EAepe - Clasif. Funcional",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "02.3.4.6",
      "nombre": "Edo. Analítico Ingresos",
      "sistema": "Presupuestos",
      "subsistema": "Imprimir",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.1.1",
      "nombre": "Plan de Cuentas",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "Catálogo",
      "estado": "Terminado",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.1.2",
      "nombre": "Matriz de Conversión",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Catálogo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.2.1",
      "nombre": "Pólizas Manuales",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "Registro",
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.2.2",
      "nombre": "Pólizas Automáticas",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "Registro",
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.2.3",
      "nombre": "Fideicomisos",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.2.4",
      "nombre": "Módulo Retenciones",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.2.5",
      "nombre": "Bóveda CFDI",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.3.1",
      "nombre": "Descarga Contable Masiva",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.3.2",
      "nombre": "Conciliación Bancaria",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.3.3",
      "nombre": "Conc. de Ministraciones",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.3.4",
      "nombre": "Presupuesto vs Contable",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.3.5",
      "nombre": "Conc. Inter-Sistemas",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.3.6",
      "nombre": "Conc. Obra Pública",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.4.1",
      "nombre": "Libro Auxiliar",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "Imprimir reportes contables",
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.4.2",
      "nombre": "Libro Diario",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 2,
      "avance_desarrollo": 1,
      "visitas": [],
      "subsistema": "Imprimir reportes contables",
      "estado": "2da Iteración",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.5.1",
      "nombre": "Balanza de Comprobación",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Imprimir reportes financieros",
      "analista_asignado": "Julio César"
    },
    {
      "id": "03.5.2",
      "nombre": "Panel de Reportes Financieros",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Imprimir reportes financieros",
      "analista_asignado": "Julio César",
      "peso_dias": 36
    },
    {
      "id": "03.5.3",
      "nombre": "Panel de Reportes Fin. (CONAC)",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Imprimir reportes financieros",
      "analista_asignado": "Julio César",
      "peso_dias": 36
    },
    {
      "id": "03.6.1",
      "nombre": "Cierre Mensual Contable",
      "sistema": "Contabilidad",
      "desarrollador_asignado": "Cristian",
      "modo_codigo": "B",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.1.1",
      "nombre": "Conceptos de Ingreso",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Catálogo",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.1.2",
      "nombre": "Cuentas Recaudadoras",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Catálogo",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.2.1",
      "nombre": "Ley de Ingresos Automática",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "A",
      "tipo_formulario": "Simple",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.2.2",
      "nombre": "Registro de Ingresos (Devengado)",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "A",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.2.3",
      "nombre": "Registro de Ingresos (Recaudado)",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "A",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 1,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.2.5",
      "nombre": "Reintegros",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Registro",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.3.1",
      "nombre": "Disponibilidad",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.3.2",
      "nombre": "Conciliación de Ingresos",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.3.3",
      "nombre": "Cierre Mensual",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Proceso",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.4.1",
      "nombre": "Edo. Analítico de Ingresos",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Imprimir",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.4.2",
      "nombre": "Auxiliar de Ingresos",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Imprimir",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "04.4.3",
      "nombre": "Recibos Oficiales",
      "sistema": "Ingresos",
      "desarrollador_asignado": "Eunice",
      "modo_codigo": "B",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "iteracion_desarrollo": 1,
      "avance_desarrollo": 0,
      "visitas": [],
      "subsistema": "Imprimir",
      "estado": "Desarrollo",
      "analista_asignado": "Julio César"
    },
    {
      "id": "05.4.1",
      "nombre": "Pre-pólizas contables",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Procesos",
      "tipo_formulario": "Simple",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.5.1",
      "nombre": "Reporte Multicriterio de Cuentas por Pagar",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Simple",
      "analisis_funcional": 0,
      "modo_codigo": "A",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.5.2",
      "nombre": "Estado de Cuenta de Gastos a Comprobar",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Simple",
      "analisis_funcional": 0,
      "modo_codigo": "A",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.1.1",
      "nombre": "Contratos",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Catálogo",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.4.2",
      "nombre": "Buzón de facturación",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Procesos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.2.1",
      "nombre": "Afectación pagos de RH automatizados",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de gasto",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.2.2",
      "nombre": "Afectación pagos de RH manuales",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de gasto",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.2.3",
      "nombre": "Afectación pagos de RM derivados de un pedido",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de gasto",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.2.4",
      "nombre": "Afectación gasto para comprobar",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de gasto",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.3.1",
      "nombre": "Órden de pagos de RH automatizados",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de órdenes de pago",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.3.2",
      "nombre": "Órden de pagos de RH manuales",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de órdenes de pago",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.3.3",
      "nombre": "Órden de pagos de RM derivados de un pedido",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de órdenes de pago",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.3.4",
      "nombre": "Órden de gastos para comprobar",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de órdenes de pago",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "05.3.5",
      "nombre": "Comprobación de gastos",
      "sistema": "Cuentas por Pagar",
      "subsistema": "Registro de órdenes de pago",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.1.1",
      "nombre": "Emisión de Suficiencia Presupuestal",
      "sistema": "Recursos Materiales",
      "subsistema": "Bloqueo",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.2.1",
      "nombre": "Registro de Contratos",
      "sistema": "Recursos Materiales",
      "subsistema": "Comprometido",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.2.2",
      "nombre": "Registro de Pedidos y Servicios",
      "sistema": "Recursos Materiales",
      "subsistema": "Comprometido",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.3.1",
      "nombre": "Interfaz Automatizada con Almacén",
      "sistema": "Recursos Materiales",
      "subsistema": "Devengado",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.3.2",
      "nombre": "Registro y Validación de Facturas",
      "sistema": "Recursos Materiales",
      "subsistema": "Devengado",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.5.1",
      "nombre": "Reporte de Disponibilidad y Suficiencia por Partida",
      "sistema": "Recursos Materiales",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.5.2",
      "nombre": "Reporte de Movimientos y Depreciación de Activos",
      "sistema": "Recursos Materiales",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.5.3",
      "nombre": "Reporte de Conciliación Contable-Almacén",
      "sistema": "Recursos Materiales",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.4.1",
      "nombre": "Obtención de póliza de inventarios",
      "sistema": "Recursos Materiales",
      "subsistema": "Procesos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.4.2",
      "nombre": "Obtención de póliza de almacén",
      "sistema": "Recursos Materiales",
      "subsistema": "Procesos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "07.6.1",
      "nombre": "Sincronización de Plantilla y Estructura",
      "sistema": "Recursos Materiales",
      "subsistema": "Catálogos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Daryl",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.1.1",
      "nombre": "Recepción y Cortes de Caja",
      "sistema": "Tesorería",
      "subsistema": "Gestión de Caja",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.1.2",
      "nombre": "Traspaso entre cuentas",
      "sistema": "Tesorería",
      "subsistema": "Gestión de Caja",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.1.3",
      "nombre": "Reintegros de un gasto a comprobar",
      "sistema": "Tesorería",
      "subsistema": "Gestión de Caja",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.2.1",
      "nombre": "Emisión de Transferencias Electrónicas (SPEI)",
      "sistema": "Tesorería",
      "subsistema": "Control de Pagos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.2.2",
      "nombre": "Emisión y Control de Cheques",
      "sistema": "Tesorería",
      "subsistema": "Control de Pagos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.2.3",
      "nombre": "Cancelación y Reintegro de Pagos",
      "sistema": "Tesorería",
      "subsistema": "Control de Pagos",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.3.1",
      "nombre": "Conciliación Bancaria Automatizada / Manual",
      "sistema": "Tesorería",
      "subsistema": "Control Bancario",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.3.2",
      "nombre": "Registro de Inversiones y Rendimientos",
      "sistema": "Tesorería",
      "subsistema": "Control Bancario",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.4.1",
      "nombre": "Reporte Analítico de Saldos Bancarios",
      "sistema": "Tesorería",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    },
    {
      "id": "06.4.2",
      "nombre": "Libro de Bancos / Listado de Pagos",
      "sistema": "Tesorería",
      "subsistema": "Consultas e Informes",
      "tipo_formulario": "Compuesto",
      "analisis_funcional": 0,
      "modo_codigo": "B",
      "estado": "Análisis",
      "desarrollador_asignado": "Eunice",
      "analista_asignado": "Julio César",
      "avance_desarrollo": 0
    }
  ]
};
